from pathlib import Path


def replace_once(path: str, old: str, new: str, label: str):
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly one match, found {count}")
    p.write_text(text.replace(old, new, 1))

# App: settings becomes the single management center; remove duplicate sidebar management pages.
replace_once(
    'src/App.tsx',
    "import { AlertTriangle, Building2, CalendarDays, FileClock, LayoutDashboard, LogOut, Settings, UserCog, Users } from 'lucide-react';",
    "import { AlertTriangle, Building2, CalendarDays, LayoutDashboard, LogOut, Settings, Users } from 'lucide-react';",
    'app icons',
)
replace_once('src/App.tsx', "import { UsersPage } from './UsersPage';\nimport { AuditPage } from './AuditPage';\n", '', 'remove duplicate management imports')
replace_once('src/App.tsx', "import { ProviderUnavailabilityPage } from './ProviderUnavailabilityPage';\n", "import { ProviderUnavailabilityPage } from './ProviderUnavailabilityPage';\nimport { SettingsHub } from './SettingsHub';\n", 'settings hub import')
replace_once('src/App.tsx', "type Page='dashboard'|'patients'|'appointments'|'provider-unavailability'|'directory'|'settings'|'users'|'audit';", "type Page='dashboard'|'patients'|'appointments'|'provider-unavailability'|'directory'|'settings';", 'page union')
replace_once('src/App.tsx', "  const [auditEmployee,setAuditEmployee]=useState('');\n", '', 'audit state')
replace_once('src/App.tsx', "  function openLifecycle(employeeCode:string){setAuditEmployee(employeeCode);navigate('audit')}\n", '', 'lifecycle navigation')
replace_once('src/App.tsx', "    try{await api.logout(session.token)}finally{sessionStorage.removeItem('clinicdesk.session');setActorToken(null);setSession(null);setPage('dashboard');setAuditEmployee('')}\n", "    try{await api.logout(session.token)}finally{sessionStorage.removeItem('clinicdesk.session');setActorToken(null);setSession(null);setPage('dashboard')}\n", 'logout cleanup')
replace_once('src/App.tsx', "        {canManage&&<button aria-current={page==='users'?'page':undefined} className={page==='users'?'active':''} onClick={()=>navigate('users')}><UserCog aria-hidden=\"true\"/>المستخدمون والصلاحيات</button>}\n        {canManage&&<button aria-current={page==='audit'?'page':undefined} className={page==='audit'?'active':''} onClick={()=>{setAuditEmployee('');navigate('audit')}}><FileClock aria-hidden=\"true\"/>سجل العمليات</button>}\n", '', 'duplicate management navigation')
replace_once('src/App.tsx', "        <small>قاعدة بيانات محلية • SQLite</small>", "        <small>ClinicDesk 5.1.0 • النسخة المجانية</small>", 'edition footer')
replace_once('src/App.tsx', "      {page==='settings'&&!restrictedClinical&&<SchedulingPage/>}\n      {page==='users'&&canManage&&<UsersPage currentUser={session.user} onLifecycle={openLifecycle}/>} \n      {page==='audit'&&canManage&&<AuditPage initialEmployeeCode={auditEmployee}/>} \n", "      {page==='settings'&&!restrictedClinical&&<SettingsHub currentUser={session.user} canManage={canManage}/>}\n", 'settings render')
replace_once('src/App.tsx', "import { SchedulingPage } from './SchedulingPage';\n", '', 'unused scheduling import')

# Main stylesheet.
replace_once('src/main.tsx', "import './provider-unavailability.css';\n", "import './provider-unavailability.css';\nimport './appointment-status.css';\n", 'appointment stylesheet import')

# Scheduling page supports being embedded inside the settings center.
replace_once('src/SchedulingPage.tsx', 'export function SchedulingPage() {', 'export function SchedulingPage({ embedded = false }: { embedded?: boolean } = {}) {', 'scheduling embedded signature')
replace_once('src/SchedulingPage.tsx', '      <div className="pageTitle"><div><h1>الإعدادات</h1><p>إعدادات المواعيد والنسخ الاحتياطي المحلي.</p></div></div>', '      {!embedded && <div className="pageTitle"><div><h1>الإعدادات</h1><p>إعدادات المواعيد والنسخ الاحتياطي المحلي.</p></div></div>}', 'scheduling embedded title')

# Patient record: linked appointments are prominent, classified, and up to 100 are visible.
replace_once('src/PatientsPage.tsx', "import { fullGregorianDate, fullGregorianDateTime } from './dateDisplay';\n", "import { fullGregorianDate, fullGregorianDateTime } from './dateDisplay';\nimport { appointmentDisplayClass, appointmentDisplayLabel, appointmentDisplayStatus } from './appointmentPresentation';\nimport { safePrint } from './safePrint';\n", 'patient imports')
replace_once('src/PatientsPage.tsx', "const status: Record<string, string> = {\n  scheduled: 'مجدول',\n  arrived: 'وصل',\n  in_progress: 'قيد الخدمة',\n  completed: 'مكتمل',\n  cancelled: 'ملغي',\n  no_show: 'لم يحضر',\n};\n", '', 'patient legacy status labels')
replace_once('src/PatientsPage.tsx', 'setHistory(await api.patientAppointments(p.id, 30));', 'setHistory(await api.patientAppointments(p.id, 100));', 'patient appointment history limit')
replace_once('src/PatientsPage.tsx', 'onClick={() => window.print()}', 'onClick={() => void safePrint()}', 'patient safe print')
old_history = '''            <section className="recordSummary">\n              <h3><CalendarDays aria-hidden="true" /> سجل المواعيد</h3>\n              {historyBusy ? <p>جارٍ تحميل المواعيد…</p> : history.length === 0 ? <p>لا توجد مواعيد مسجلة لهذا المريض.</p> : (\n                <div className="patientHistory">{history.map((a) => (\n                  <article key={a.id}><Clock3 aria-hidden="true" /><span><strong>{fullGregorianDateTime(a.startsAt)}</strong><small>{a.clinicName || 'بدون عيادة'}{a.doctorName ? ` • ${a.doctorName}` : ''}</small></span><em className={`status status-${a.status}`}>{status[a.status] || a.status}</em></article>\n                ))}</div>\n              )}\n            </section>\n'''
replace_once('src/PatientsPage.tsx', old_history, '', 'remove buried appointment history')
patient_anchor = '            <section className="recordSummary"><h3>المعلومات الطبية المختصرة</h3><p>{details.medicalSummary || \'لا توجد معلومات طبية مختصرة مسجلة.\'}</p></section>\n'
patient_panel = '''            <section className="patientHistoryProminent">\n              <h3><CalendarDays aria-hidden="true" /> المواعيد المرتبطة بهذا الملف</h3>\n              <p>القادمة والفائتة والحالات النهائية تظهر هنا داخل ملف المريض نفسه.</p>\n              {historyBusy ? <p>جارٍ تحميل المواعيد…</p> : history.length === 0 ? <p>لا توجد مواعيد مسجلة لهذا المريض.</p> : <>\n                <div className="patientAppointmentSummary">\n                  <div><small>قادم</small><strong>{history.filter((a) => ['upcoming','due_now'].includes(appointmentDisplayStatus(a))).length}</strong></div>\n                  <div><small>فائت</small><strong>{history.filter((a) => appointmentDisplayStatus(a) === 'overdue').length}</strong></div>\n                  <div><small>مكتمل</small><strong>{history.filter((a) => appointmentDisplayStatus(a) === 'completed').length}</strong></div>\n                  <div><small>لم يحضر</small><strong>{history.filter((a) => appointmentDisplayStatus(a) === 'no_show').length}</strong></div>\n                </div>\n                <div className="patientTimeline">{history.map((a) => (\n                  <article key={a.id}><Clock3 aria-hidden="true" /><span><strong>{fullGregorianDateTime(a.startsAt)}</strong><small>{a.clinicName || 'بدون عيادة'}{a.doctorName ? ` • ${a.doctorName}` : ''}</small></span><em className={appointmentDisplayClass(a)}>{appointmentDisplayLabel(a)}</em></article>\n                ))}</div>\n              </>}\n            </section>\n'''
replace_once('src/PatientsPage.tsx', patient_anchor, patient_panel + patient_anchor, 'prominent patient appointment panel')

# Appointment page: one presentation source and guarded printing.
replace_once('src/AppointmentsPage.tsx', "import { fullGregorianDate, fullGregorianDateTime } from './dateDisplay';\n", "import { fullGregorianDate, fullGregorianDateTime } from './dateDisplay';\nimport { appointmentDisplayClass, appointmentDisplayLabel } from './appointmentPresentation';\nimport { safePrint } from './safePrint';\n", 'appointment imports')
replace_once('src/AppointmentsPage.tsx', "const labels: Record<string, string> = {\n  scheduled: 'مجدول',\n  arrived: 'وصل',\n  in_progress: 'قيد الخدمة',\n  completed: 'مكتمل',\n  cancelled: 'ملغي',\n  no_show: 'لم يحضر',\n};\n", '', 'appointment legacy labels')
replace_once('src/AppointmentsPage.tsx', 'onClick={() => window.print()}', 'onClick={() => void safePrint()}', 'appointment safe print')
replace_once('src/AppointmentsPage.tsx', '<td><span className={`status status-${a.status}`}>{labels[a.status] || a.status}</span></td>', '<td><span className={appointmentDisplayClass(a)}>{appointmentDisplayLabel(a)}</span></td>', 'appointment status presentation')

# Read-only appointment view follows the same rules.
replace_once('src/ReadOnlyAppointmentsPage.tsx', "import { fullGregorianDate, fullGregorianDateTime } from './dateDisplay';\n", "import { fullGregorianDate, fullGregorianDateTime } from './dateDisplay';\nimport { appointmentDisplayClass, appointmentDisplayLabel } from './appointmentPresentation';\nimport { safePrint } from './safePrint';\n", 'readonly imports')
replace_once('src/ReadOnlyAppointmentsPage.tsx', "const labels:Record<string,string>={scheduled:'مجدول',arrived:'وصل',in_progress:'قيد الخدمة',completed:'مكتمل',cancelled:'ملغي',no_show:'لم يحضر'};\n", '', 'readonly legacy labels')
replace_once('src/ReadOnlyAppointmentsPage.tsx', 'onClick={()=>window.print()}', 'onClick={()=>void safePrint()}', 'readonly safe print')
replace_once('src/ReadOnlyAppointmentsPage.tsx', '<td><span className={`status status-${a.status}`}>{labels[a.status]||a.status}</span></td>', '<td><span className={appointmentDisplayClass(a)}>{appointmentDisplayLabel(a)}</span></td>', 'readonly status presentation')

# Backend overdue query: overdue is derived from scheduled + past end time and is never auto-converted to no_show.
replace_once('src-tauri/src/appointments.rs', 'pub fn list_for_patient(\n', '''pub fn list_overdue(c: &Connection, to: &str, limit: i64) -> Result<Vec<Appointment>, String> {\n    let sql = format!("{SELECT} WHERE a.status='scheduled' AND a.ends_at<?1 ORDER BY a.ends_at DESC LIMIT ?2");\n    let mut s = c.prepare(&sql).map_err(|e| e.to_string())?;\n    let rows = s\n        .query_map(params![to, limit.clamp(1, 500)], map)\n        .map_err(|e| e.to_string())?;\n    rows.collect::<Result<Vec<_>, _>>().map_err(|e| e.to_string())\n}\npub fn list_for_patient(\n''', 'backend overdue query')

lib_anchor = '''#[tauri::command]\nfn appointment_upcoming_all(\n'''
lib_command = '''#[tauri::command]\nfn appointment_overdue_history(\n    db: tauri::State<Db>,\n    actor_token: Option<String>,\n    to: String,\n) -> Result<Vec<appointments::Appointment>, String> {\n    authorize_command(&db, actor_token.as_deref(), authorization::APPOINTMENT_READ)?;\n    with_db(&db, |c| appointments::list_overdue(c, &to, 500))\n}\n'''
replace_once('src-tauri/src/lib.rs', lib_anchor, lib_command + lib_anchor, 'overdue command')
replace_once('src-tauri/src/lib.rs', '            appointment_missed_history,\n            appointment_upcoming_all,', '            appointment_missed_history,\n            appointment_overdue_history,\n            appointment_upcoming_all,', 'overdue handler registration')
replace_once('src/api.ts', "missedAppointments:(to:string)=>authed<Appointment[]>('appointment_missed_history',{to}),upcomingAppointments", "missedAppointments:(to:string)=>authed<Appointment[]>('appointment_missed_history',{to}),overdueAppointments:(to:string)=>authed<Appointment[]>('appointment_overdue_history',{to}),upcomingAppointments", 'overdue frontend API')

# Dashboard: overdue becomes its own filter and alert, and presentation is shared.
replace_once('src/Dashboard.tsx', "import { fullGregorianDateTime } from './dateDisplay';\n", "import { fullGregorianDateTime } from './dateDisplay';\nimport { appointmentDisplayClass, appointmentDisplayLabel, appointmentDisplayStatus } from './appointmentPresentation';\n", 'dashboard presentation import')
replace_once('src/Dashboard.tsx', "const labels: Record<string, string> = {\n  scheduled: 'مجدول',\n  arrived: 'وصل',\n  in_progress: 'قيد الخدمة',\n  completed: 'مكتمل',\n  cancelled: 'ملغي',\n  no_show: 'لم يحضر',\n};\n", '', 'dashboard legacy labels')
replace_once('src/Dashboard.tsx', "type Filter = 'today' | 'week' | 'missed' | 'renewal' | 'threeMonths' | 'upcoming';", "type Filter = 'today' | 'week' | 'overdue' | 'missed' | 'renewal' | 'threeMonths' | 'upcoming';", 'dashboard filter type')
replace_once('src/Dashboard.tsx', "  missed: 'لم يحضر',\n", "  overdue: 'فائت',\n  missed: 'لم يحضر',\n", 'overdue filter label')
replace_once('src/Dashboard.tsx', "  const [missedRows, setMissedRows] = useState<Appointment[]>([]);\n", "  const [missedRows, setMissedRows] = useState<Appointment[]>([]);\n  const [overdueRows, setOverdueRows] = useState<Appointment[]>([]);\n", 'overdue state')
replace_once('src/Dashboard.tsx', "      api.missedAppointments(`${today}T00:00:00`),\n      api.followUps", "      api.missedAppointments(`${today}T00:00:00`),\n      api.overdueAppointments(`${today}T00:00:00`),\n      api.followUps", 'overdue request')
replace_once('src/Dashboard.tsx', ".then(([a, next, range, upcoming, missed, followUpRows, totalPatients, inactivePatients]) => {", ".then(([a, next, range, upcoming, missed, overdue, followUpRows, totalPatients, inactivePatients]) => {", 'overdue result')
replace_once('src/Dashboard.tsx', "        setMissedRows(missed);\n        setFollowUps", "        setMissedRows(missed);\n        setOverdueRows(overdue);\n        setFollowUps", 'overdue set state')
replace_once('src/Dashboard.tsx', "  const waiting = rows.filter((a) => ['scheduled', 'arrived'].includes(a.status)).length;", "  const waiting = rows.filter((a) => ['upcoming', 'due_now', 'arrived'].includes(appointmentDisplayStatus(a))).length;", 'waiting excludes overdue')
replace_once('src/Dashboard.tsx', "    if (filter === 'missed') return missedRows;\n", "    if (filter === 'overdue') return overdueRows;\n    if (filter === 'missed') return missedRows;\n", 'overdue filtering')
replace_once('src/Dashboard.tsx', "  }, [filter, rows, rangeRows, upcomingRows, missedRows]);", "  }, [filter, rows, rangeRows, upcomingRows, missedRows, overdueRows]);", 'overdue memo deps')
replace_once('src/Dashboard.tsx', "  const alertCount = alerts.length + inactive.length;", "  const alertCount = alerts.length + overdueRows.length + inactive.length;", 'overdue alert count')
replace_once('src/Dashboard.tsx', "                    {inactive.slice(0, 8).map((p) => (", "                    {overdueRows.slice(0, 8).map((a) => (\n                      <button key={`overdue-${a.id}`} type=\"button\" onClick={() => onPatient(a.fileNo)}>\n                        <Clock3 aria-hidden=\"true\" />\n                        <span><b>{a.patientName}</b><small>موعد فائت • ملف <bdi>{a.fileNo}</bdi> • {fullGregorianDateTime(a.startsAt)}</small></span>\n                      </button>\n                    ))}\n                    {inactive.slice(0, 8).map((p) => (", 'overdue alert rows')
replace_once('src/Dashboard.tsx', '<em className={`status status-${a.status}`}>{labels[a.status] || a.status}</em>', '<em className={appointmentDisplayClass(a)}>{appointmentDisplayLabel(a)}</em>', 'dashboard status presentation')

# UI contract: stop protecting obsolete wiring and require the real settings/print behaviors.
p = Path('scripts/ui-contract.mjs')
s = p.read_text()
s = s.replace("  audit: read('src/AuditPage.tsx'),\n", "  audit: read('src/AuditPage.tsx'),\n  settingsHub: read('src/SettingsHub.tsx'),\n  safePrint: read('src/safePrint.ts'),\n  appointmentPresentation: read('src/appointmentPresentation.ts'),\n")
s = s.replace("t.api.includes(\"changePassword:(token:string,currentPassword:string,newPassword:string)=>invoke<UserSummary>('auth_validate_session',{token,currentPassword,newPassword})\")", "t.api.includes(\"changePassword:(token:string,currentPassword:string,newPassword:string)=>invoke<UserSummary>('auth_change_password',{actorToken:token,currentPassword,newPassword})\")")
s = s.replace("['users and lifecycle navigation are role gated', files.app.includes('المستخدمون والصلاحيات') && files.app.includes('سجل العمليات') && t.app.includes(\"session?.user.roleType==='general_manager'||session?.user.roleType==='deputy_manager'\")],", "['users permissions and lifecycle are inside the settings center', files.settingsHub.includes('المستخدمون والصلاحيات') && files.settingsHub.includes('سجل العمليات') && t.app.includes('<SettingsHubcurrentUser={session.user}canManage={canManage}/>')],")
s = s.replace("['patient record has print action', t.patients.includes('onClick={()=>window.print()}') && files.patients.includes('طباعة الملف')],", "['patient record uses guarded print action', t.patients.includes('onClick={()=>voidsafePrint()}') && files.patients.includes('طباعة الملف') && files.safePrint.includes('onCloseRequested')],")
s = s.replace("['appointment day has print action', t.appointments.includes('onClick={()=>window.print()}') && files.appointments.includes('طباعة اليوم')],", "['appointment day uses guarded print action', t.appointments.includes('onClick={()=>voidsafePrint()}') && files.appointments.includes('طباعة اليوم') && files.safePrint.includes('clinicdeskPrinting')],")
p.write_text(s)

# A focused visible-feature gate prevents code-only completion.
Path('scripts/visible-feature-contract.mjs').write_text(r'''import { readFileSync } from 'node:fs';\nconst read=(p)=>readFileSync(p,'utf8');\nconst files={app:read('src/App.tsx'),settings:read('src/SettingsHub.tsx'),patients:read('src/PatientsPage.tsx'),appointments:read('src/AppointmentsPage.tsx'),dashboard:read('src/Dashboard.tsx'),readonly:read('src/ReadOnlyAppointmentsPage.tsx'),presentation:read('src/appointmentPresentation.ts'),print:read('src/safePrint.ts'),api:read('src/api.ts'),rust:read('src-tauri/src/appointments.rs'),lib:read('src-tauri/src/lib.rs')};\nconst checks=[\n['settings exposes users',files.settings.includes('المستخدمون والصلاحيات')&&files.settings.includes('<UsersPage')],\n['settings exposes audit',files.settings.includes('سجل العمليات')&&files.settings.includes('<AuditPage')],\n['free edition visible',files.app.includes('النسخة المجانية')&&files.settings.includes('النسخة المجانية')],\n['patient file contains linked appointments',files.patients.includes('المواعيد المرتبطة بهذا الملف')&&files.patients.includes('api.patientAppointments(p.id, 100)')],\n['overdue label is distinct',files.presentation.includes("overdue: 'فائت'")&&files.dashboard.includes("overdue: 'فائت'")],\n['overdue backend remains scheduled',files.rust.includes("a.status='scheduled'")&&files.rust.includes('list_overdue')],\n['overdue alert visible',files.dashboard.includes('موعد فائت')&&files.api.includes('appointment_overdue_history')],\n['shared status presentation used in all appointment surfaces',files.patients.includes('appointmentDisplayLabel(a)')&&files.appointments.includes('appointmentDisplayLabel(a)')&&files.readonly.includes('appointmentDisplayLabel(a)')&&files.dashboard.includes('appointmentDisplayLabel(a)')],\n['printing guards main window close',files.print.includes('onCloseRequested')&&files.print.includes('event.preventDefault()')],\n['patient printing uses guard',files.patients.includes('void safePrint()')],\n['appointment printing uses guard',files.appointments.includes('void safePrint()')&&files.readonly.includes('void safePrint()')],\n['settings page is the management hub',files.app.includes('<SettingsHub currentUser={session.user} canManage={canManage}/>')],\n];\nlet failed=0; for(const [name,ok] of checks){console.log(`${ok?'PASS':'FAIL'} ${name}`);if(!ok)failed++;} if(failed){console.error(`Visible feature contract failed: ${failed}`);process.exit(1);} console.log(`Visible feature contract passed: ${checks.length}/${checks.length}`);\n''')
