use rusqlite::{params,Connection,OptionalExtension};use serde::{Deserialize,Serialize};
#[derive(Debug,Serialize)]#[serde(rename_all="camelCase")]pub struct Clinic{pub id:i64,pub name:String,pub phone:Option<String>,pub address:Option<String>,pub is_active:bool}
#[derive(Debug,Deserialize)]#[serde(rename_all="camelCase")]pub struct ClinicInput{pub name:String,pub phone:Option<String>,pub address:Option<String>}
#[derive(Debug,Serialize)]#[serde(rename_all="camelCase")]pub struct Doctor{pub id:i64,pub clinic_id:Option<i64>,pub name:String,pub specialty:Option<String>,pub phone:Option<String>,pub is_active:bool}
#[derive(Debug,Deserialize)]#[serde(rename_all="camelCase")]pub struct DoctorInput{pub clinic_id:Option<i64>,pub name:String,pub specialty:Option<String>,pub phone:Option<String>}
fn clean(v:Option<String>)->Option<String>{v.map(|x|x.trim().to_string()).filter(|x|!x.is_empty())}
pub fn list_clinics(c:&Connection)->Result<Vec<Clinic>,String>{let mut s=c.prepare("SELECT id,name,phone,address,is_active FROM clinics WHERE is_active=1 ORDER BY name").map_err(|e|e.to_string())?;s.query_map([],|r|Ok(Clinic{id:r.get(0)?,name:r.get(1)?,phone:r.get(2)?,address:r.get(3)?,is_active:r.get::<_,i64>(4)?==1})).map_err(|e|e.to_string())?.collect::<Result<Vec<_>,_>>().map_err(|e|e.to_string())}
pub fn create_clinic(c:&Connection,i:ClinicInput)->Result<Clinic,String>{let name=i.name.trim();if name.len()<2{return Err("اسم العيادة مطلوب".into())}c.execute("INSERT INTO clinics(name,phone,address)VALUES(?1,?2,?3)",params![name,clean(i.phone),clean(i.address)]).map_err(|e|e.to_string())?;let id=c.last_insert_rowid();c.query_row("SELECT id,name,phone,address,is_active FROM clinics WHERE id=?1",[id],|r|Ok(Clinic{id:r.get(0)?,name:r.get(1)?,phone:r.get(2)?,address:r.get(3)?,is_active:r.get::<_,i64>(4)?==1})).map_err(|e|e.to_string())}
pub fn list_doctors(c:&Connection)->Result<Vec<Doctor>,String>{let mut s=c.prepare("SELECT id,clinic_id,name,specialty,phone,is_active FROM doctors WHERE is_active=1 ORDER BY name").map_err(|e|e.to_string())?;s.query_map([],|r|Ok(Doctor{id:r.get(0)?,clinic_id:r.get(1)?,name:r.get(2)?,specialty:r.get(3)?,phone:r.get(4)?,is_active:r.get::<_,i64>(5)?==1})).map_err(|e|e.to_string())?.collect::<Result<Vec<_>,_>>().map_err(|e|e.to_string())}
pub fn create_doctor(c:&Connection,i:DoctorInput)->Result<Doctor,String>{let name=i.name.trim();if name.len()<2{return Err("اسم الطبيب مطلوب".into())}if let Some(cid)=i.clinic_id{let exists:Option<i64>=c.query_row("SELECT id FROM clinics WHERE id=?1 AND is_active=1",[cid],|r|r.get(0)).optional().map_err(|e|e.to_string())?;if exists.is_none(){return Err("العيادة المحددة غير موجودة".into())}}c.execute("INSERT INTO doctors(clinic_id,name,specialty,phone)VALUES(?1,?2,?3,?4)",params![i.clinic_id,name,clean(i.specialty),clean(i.phone)]).map_err(|e|e.to_string())?;let id=c.last_insert_rowid();c.query_row("SELECT id,clinic_id,name,specialty,phone,is_active FROM doctors WHERE id=?1",[id],|r|Ok(Doctor{id:r.get(0)?,clinic_id:r.get(1)?,name:r.get(2)?,specialty:r.get(3)?,phone:r.get(4)?,is_active:r.get::<_,i64>(5)?==1})).map_err(|e|e.to_string())}
